@startuml

title MOD4B - Class Diagram

package application {
    
  class Simulation {
    - hours: int
    - passengers: int
  }

  package menu {
    
    interface Menu {
    }

    class Main implements Menu {
    }

    class Runway implements Menu {
    }

    class WaitingPlanes implements Menu {
    }

    class AdvanceHour implements Menu {
    }
  
  }  

  package request {
    
    interface Request {
      - rarity: Double
      - title: String
      - description: String
      - options: Option[] or ArrayList<Option>
    }
    
    abstract Landing implements Request {
    }

    class PlaneLanding implements Landing {
    }

    class EmergencyLanding implements Landing {
    }

    class FundingEvent implements Request {
    }

    class JumboJet implements Landing {
    }

    class BadWeather implements Request {
    }

    class SnakesOnThePlane implements Request {
    }

    class Protests implements Request {
    }

    class JohnMcClain implements Request {
    }
  }
  
  package options {
  
    interface Option {
      - description: String
      - requirement: Requirement
      - consequence: Consequence
    }
    
    class Requirement {
      - description: String
      --
      + checkRequirement(): boolean
    }
    
    class Consequence {
      - description: String
      --
      + applyConsequence(): void
    }
    
    class AllowLanding implements Option {
    }
    
    class PlaceOnStandby implements Option {
    }
    
    class EmptyRandomRunway implements Option {
    }
    
    class RescueTeam implements Option {
    }
    
    class AirRefueling implements Option {
    }
    
    class CrossWinds implements Option {
    }
    
    class IcyRunWays implements Option {
    }
    
    class IceStorm implements Option {
    }
    
    class LetThemLand implements Option {
    }
    
    class RefuseThem implements Option {
    }
    
    class AllowThemTheSpaceToProtest implements Option {
    }
    
    class GetPoliceInvolved implements Option {
    }
    
    class LetThePlanesLandAnyways implements Option {
    }
    
    class LockdownTheRunway implements Option {
    }
    
    class LetTheManGo implements Option {
    }
  
  }

  Menu -up-> Simulation
  Request -up-> Simulation
  Request "1..*" -- "2..*" Option
  Option -- Requirement
  Option -- Consequence
  
}

@enduml
